### ISSUE TITLE
Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by psychobmw98** [Zenoixnoize/GARFIELD-WHATSAPP-BOT-v8#5]
Hello, have successifully deployed the app to heroku.
unfortunately each time i send .menu or .help the bot brings am error.

TypeError: Cannot read properties of undefined (reading 'toString')
    at Object.getStream (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:196:18)
    at Object.encryptedStream (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:232:44) 
    at prepareWAMessageMedia (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:70:132)
    at Object._0x1fb99c.<computed> [as send5ButImg] (/app/index.js:1:15393)
    at GarfieldNeural (/app/Garfield.js:1:280063)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Zenoixnoize** [comment]
# That error has been fixed. Fork again

**Comment by zaheer1122** [comment]
Starting November 28th, 2022, free Heroku Dynos, free Heroku Postgres, and free Heroku Data for Redis® will no longer be available.
If you have apps using any of these resources, you must upgrade to paid plans by this date to ensure your apps continue to run and to retain your data. For students, we will announce a new program by the end of September.  [Learn more](https://blog.heroku.com/next-chapter)
